In [2]:
import numpy as np

In [4]:
# a = np.array([ _ for _ in range(12, 24)])
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [26]:
arrays_list = []
arrays_list.extend([a.reshape(i, 12 // i) for i in [2, 3, 4, 6, 12]])

print('Пять массивов различной формы:\n')
for array in arrays_list:
    print(array, '\n')

Пять массивов различной формы:

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]] 

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]] 

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]] 



In [30]:
arrays_list = []
arrays_list.extend([a.reshape(i, -1) for i in [2, 3, 4]])
arrays_list.extend([a.reshape(-1, i) for i in [2, 1]])

print('Пять массивов различной формы:\n')
for array in arrays_list:
    print(array, '\n')

Пять массивов различной формы:

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]] 

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]] 

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]] 



In [35]:
print(f'Массив, имеющий 12 строк и 1 столбец в numpy имеет размерность {arrays_list[-1].ndim}')

Массив, имеющий 12 строк и 1 столбец в numpy имеет размерность 2


In [45]:
array = np.random.randn(3, 4)
print(f'исходный массив size = {array.size}:\n {array}')
print()
print(f'одномерный массив size = {array.flatten().size}:\n {array.flatten()}')

исходный массив size = 12:
 [[ 0.41515898 -1.25867348 -0.55865322 -1.29138299]
 [ 0.79018296  1.88785806 -0.3885434   0.99899814]
 [ 0.0998886   0.8152355  -1.60493243  1.23258648]]

одномерный массив size = 12:
 [ 0.41515898 -1.25867348 -0.55865322 -1.29138299  0.79018296  1.88785806
 -0.3885434   0.99899814  0.0998886   0.8152355  -1.60493243  1.23258648]


### Задача 6.
Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2.
В чем разница между массивами a и b?

In [56]:
a = np.arange(20, 0, -2)
a.shape

(10,)

In [55]:
b = np.arange(20, 1, -2).reshape(1, 10)
b.shape

(1, 10)

### Задача 7.

Вертикально соединить массивы a и b. a - двумерный массив из нулей, 
число строк которого больше 1 и на 1 меньше, чем число строк двумерного 
массива b, состоящего из единиц.<br><br>
Решение:
чтобы найти размерности массивов решим простую систему уравнений:<br>
ja = jb = j - равенство столбцов, обязателное условие вертикалного соединения массивов
<br><br>
ia + 1 = ib<br>
(ia + ib) * j = 10 - количество элементов результирующего массива
<br><br>
Получили 3 переменные и 2 уравнения. Однако с учетом ограничений ia, ib, j - целые числа можно найти решение системы:<br>
ia = 2<br>
ib = 3<br>
j = 2

In [68]:
a = np.zeros((2, 2))
b = np.ones((3, 2))

v = np.vstack((a, b))
print(v, '\n')
print(f'size = {v.size}')

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 

size = 10


### Задача 8

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.<br>
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 
4 строк и 3 столбцов.<br>
Получить матрицу At путем транспонирования матрицы A.<br>
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.<br><br>
Какой размер имеет матрица B?
Получится ли вычислить обратную матрицу для матрицы B и почему?

In [76]:
a = np.arange(12)
A = a.reshape((4, 3))
At = A.T
B = np.dot(A, At)
print(A)
print()
print(At)
print()
print(B)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [88]:
print(f'Размерность матрицы определеляется кол-вом строк 1 матрицы и столбцов 2: {A.shape[0]}X{At.shape[1]}\nКоличество элементов: {B.size}')
print()

if np.linalg.det(B) == 0:
    print(f'Определитель матрицы равен 0, матрица вырожденная, обратная матрица не существует.')

Размерность матрицы определеляется кол-вом строк 1 матрицы и столбцов 2: 4X4
Количество элементов: 16

Определитель матрицы равен 0, матрица вырожденная, обратная матрица не существует.


### Задача 9.

Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.<br>
Создайте одномерный массив c, составленный из последовательности 16-ти случайных целых чисел от 0 до 16 невключительно.<br><br>
Поменяйте его форму так, чтобы получилась квадратная матрица C.<br>
Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.<br>
Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [95]:
np.random.seed(42)
array = np.random.randint(0, 16, 16)
C = array.reshape(4, 4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [98]:
D = np.dot(C, 10) + B
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [106]:
print('Определитель: ', np.linalg.det(D))
print('Ранг: ', np.linalg.matrix_rank(D))
print('\nОбратная матрица:\n', np.linalg.inv(D))

Определитель:  -28511999.999999944
Ранг:  4

Обратная матрица:
 [[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


### Задача 10


Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице.<br>
Убедитесь, что в матрице D_inv остались только нули и единицы.<br><br>
С помощью функции numpy.where, используя матрицу D_inv в качестве маски,
а матрицы B и C - в качестве источников данных,
получите матрицу E размером 4x4.<br><br>
Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1,
должны быть равны соответствующему элементу матрицы B,<br>
а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0,
должны быть равны соответствующему элементу матрицы C.

In [108]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

In [111]:
D_inv[np.where(D_inv > 0)] = 1
D_inv[np.where(D_inv < 0)] = 0
D_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [114]:
E = np.where(D_inv > 0, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])

## Задание 2

Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.<br>
Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7.<br><br>
Будем считать, что каждый столбец - это признак, а строка - наблюдение.<br>
Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy.<br>
Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [9]:
a = np.array(list(zip((1, 2, 3, 3, 1), (6, 8, 11, 10, 7))))
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [12]:
a_mean = a.mean(axis=0)
a_mean

array([2. , 8.4])

## Задание 3

Вычислите массив a_centered, отняв от значений массива а 
средние значения соответствующих признаков, содержащиеся в массиве mean_a.
Вычисление должно производиться в одно действие.
Получившийся массив должен иметь размер 5x2.

In [15]:
a_centered = a - a_mean
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## Задание 4

Найдите скалярное произведение столбцов массива a_centered.<br>
В результате должна получиться величина a_centered_sp. <br>
Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [29]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
a_cov = a_centered_sp / (len(a_centered) - 1)
a_cov

2.0

## Задание 5

Число, которое мы получили в конце задания 3 является 
ковариацией двух признаков, содержащихся в массиве а.<br><br>
В задании 4 мы делили сумму произведений центрированных 
признаков на N-1, а не на N, поэтому полученная нами величина 
является несмещенной оценкой ковариации.<br><br>

В этом задании проверьте получившееся число, вычислив
ковариацию еще одним способом - с помощью функции np.cov.<br>
В качестве аргумента m функция np.cov должна принимать транспонированный массив a.
В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение 
ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [31]:
cov_matrix = np.cov(a.T)
print(cov_matrix)
print(f'covarience = {cov_matrix[0, 1]}')

[[1.  2. ]
 [2.  4.3]]
covarience = 2.0
